version: "3"
services:
  db:
    build:
      context: './../db'
    env_file:
      - ./../../.env
    image: homeostasis-erp-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app
  docs-db:
    image: postgres:11-alpine
    env_file:
      - ./.env.docs
    ports:
      - "5433:5432"
    logging:
      driver: "none"
    restart: unless-stopped
    networks:
      - app
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - docs-db
    env_file:
      - ./.env.docs
    restart: unless-stopped
    ports:
      - "81:3000"
    networks:
      - app
networks: 
  app:
  docs: