version: "3.9"
services:
  db:
    build:
      context: './db'
    image: "grower_erp_db"
    restart: always
    env_file:
      - ./.env
    expose:
      - "5432"
  web:
    restart: always
    image: grower_erp_web
    build:
      context: ./
      dockerfile: ./web/Dockerfile
    env_file:
        - ./.env
    depends_on:
        - db
    ports:
        - "80:3000"