services:
  db:
    build:
      context: './../db'
    env_file:
      - ./../../.env.production
    image: homeostasis-erp-db
    restart: always
    ports:
      - "5432:5432"
  web:
    restart: always
    image: blarsy/homeostasis:0.0.1
    env_file:
      - ./../../.env.production
    depends_on:
        - db
    ports:
        - "3000"
  proxy:
    build:
      context: './../proxy'
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/www:/var/www
      - /etc/letsencrypt:/var/local