services:
  db:
    build:
      context: './../db'
    env_file:
      - ./../../.env.production
    image: grower-erp-db
    restart: always
    ports:
      - "5432:5432"
  web:
    restart: always
    image: blarsy/grower-erp:0.0.5
    build:
      context: ./../../
      dockerfile: ./docker/web/Dockerfile
    depends_on:
        - db
    ports:
        - "80:3000"